version: '3'

services:
  rest-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  soap-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: node soap-server.js